datadog:
  datadog:
    clusterName: gke-itdp-prod-sole
    tags: [manawa-cluster:gke-itdp-prod-sole, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-itdp-prod-sole
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-itdp-prod-sole
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-itdp-prod-sole
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-itdp-prod-sole
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-itdp-prod-sole
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-itdp-prod-sole
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-itdp-prod-sole
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-itdp-prod-sole
      manawa/environment: prod
