datadog:
  datadog:
    clusterName: gke-mutu-dev-laqa
    tags: [manawa-cluster:gke-mutu-dev-laqa, managed_by:observability_team, cluster_slo:true, obs-env:dev]
  agents:
    podLabels:
      manawa/cluster_name: gke-mutu-dev-laqa
      manawa/environment: dev
    podAnnotations:
      manawa/cluster_name: gke-mutu-dev-laqa
      manawa/environment: dev
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-mutu-dev-laqa
      manawa/environment: dev
    podAnnotations:
      manawa/cluster_name: gke-mutu-dev-laqa
      manawa/environment: dev
    additionalLabels:
      manawa/cluster_name: gke-mutu-dev-laqa
      manawa/environment: dev
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-mutu-dev-laqa
      manawa/environment: dev
    podAnnotations:
      manawa/cluster_name: gke-mutu-dev-laqa
      manawa/environment: dev
    additionalLabels:
      manawa/cluster_name: gke-mutu-dev-laqa
      manawa/environment: dev