datadog:
  datadog:
    clusterName: gke-hf3p-prod-kofu
    tags: [manawa-cluster:gke-hf3p-prod-kofu, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-hf3p-prod-kofu
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-hf3p-prod-kofu
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-hf3p-prod-kofu
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-hf3p-prod-kofu
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-hf3p-prod-kofu
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-hf3p-prod-kofu
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-hf3p-prod-kofu
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-hf3p-prod-kofu
      manawa/environment: prod
