datadog:
  datadog:
    clusterName: gke-ualm-nprd-wine
    tags: [manawa-cluster:gke-ualm-nprd-wine, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-ualm-nprd-wine
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-ualm-nprd-wine
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-ualm-nprd-wine
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-ualm-nprd-wine
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-ualm-nprd-wine
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-ualm-nprd-wine
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-ualm-nprd-wine
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-ualm-nprd-wine
      manawa/environment: prep
