datadog:
  datadog:
    clusterName: gke-ptlm-prod-sasu
    tags: [manawa-cluster:gke-ptlm-prod-sasu, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-ptlm-prod-sasu
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-ptlm-prod-sasu
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-ptlm-prod-sasu
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-ptlm-prod-sasu
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-ptlm-prod-sasu
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-ptlm-prod-sasu
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-ptlm-prod-sasu
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-ptlm-prod-sasu
      manawa/environment: prod
