datadog:
  apmtraceportforward: true
  datadog:
    clusterName: nprd-10-b10b
    tags: [manawa-cluster:nprd-10-b10b, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
    otlp:
      receiver:
        protocols:
          # datadog.otlp.receiver.protocols.grpc - OTLP/gRPC configuration
          grpc:
            # datadog.otlp.receiver.protocols.grpc.enabled -- Enable the OTLP/gRPC endpoint
            enabled: true
            # datadog.otlp.receiver.procotols.grpc.endpoint -- OTLP/gRPC endpoint
            endpoint: "0.0.0.0:4317"

          # datadog.otlp.receiver.protocols.http - OTLP/HTTP configuration
          http:
            # datadog.otlp.receiver.protocols.http.enabled -- Enable the OTLP/HTTP endpoint
            enabled: true
            # datadog.otlp.receiver.protocols.http.endpoint -- OTLP/HTTP endpoint
            endpoint: "0.0.0.0:4318"
  agents:
    podLabels:
      manawa/cluster_name: nprd-10-b10b
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: nprd-10-b10b
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: nprd-10-b10b
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: nprd-10-b10b
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: nprd-10-b10b
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: nprd-10-b10b
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: nprd-10-b10b
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: nprd-10-b10b
      manawa/environment: prep
