datadog:
  datadog:
    clusterName: gke-pdp-prod-kplc
    tags: [manawa-cluster:gke-pdp-prod-kplc, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  clusterAgent:
    metricsProvider:
      enabled: true
      # clusterAgent.metricsProvider.useDatadogMetrics
      # Enable usage of DatadogMetric CRD to autoscale on arbitrary Datadog queries
      useDatadogMetrics: true
    podAnnotations:
      ad.datadoghq.com/cluster-agent.check_names: '["prometheus"]'
      ad.datadoghq.com/cluster-agent.init_configs: '[{}]'
      ad.datadoghq.com/cluster-agent.instances: |
            [{
              "prometheus_url": "http://%%host%%:5000/metrics",
              "namespace": "datadog.cluster_agent",
              "max_returned_metrics": "20000",
              "metrics": [
                "go_goroutines", "go_memstats_*", "process_*",
                "api_requests",
                "datadog_requests", "external_metrics",
                "cluster_checks_*"
              ]
            }]
      manawa/product_id: '2606f0c1-477b-4f83-b275-0dc81954de2e'
      manawa/cluster_name: gke-pdp-prod-kplc
      manawa/environment: prod
    deploymentAnnotations:
      manawa/cluster_name: gke-pdp-prod-kplc
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-pdp-prod-kplc
      manawa/environment: prod
  clusterChecksRunner:
    replicas: 2
    priorityClassName: datadog-priority-class
    resources:
      requests:
        cpu: 400m
        memory: 1024Mi
      limits:
        cpu: 1200m
        memory: 8000Mi
    deploymentAnnotations:
      manawa/cluster_name: gke-pdp-prod-kplc
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-pdp-prod-kplc
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-pdp-prod-kplc
      manawa/environment: prod
  agents:
    podLabels:
      manawa/cluster_name: gke-pdp-prod-kplc
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-pdp-prod-kplc
      manawa/environment: prod
