datadog:
  global:
    cloud_provider: gke
  datadog:
    clusterName: gke-obs-nprd-rock
    tags: [manawa-cluster:gke-obs-nprd-rock, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
    # kubeStateMetricsCore:
    #   useClusterCheckRunners: false
  agents:
    podLabels:
      manawa/cluster_name: gke-obs-nprd-rock
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-obs-nprd-rock
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-obs-nprd-rock
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-obs-nprd-rock
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-obs-nprd-rock
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-obs-nprd-rock
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-obs-nprd-rock
      manawa/environment: prep
      ph: deployment
    additionalLabels:
      manawa/cluster_name: gke-obs-nprd-rock
      manawa/environment: prep
