datadog:
  datadog:
    clusterName: gke-scdp-prod-yuio
    tags: [manawa-cluster:gke-scdp-prod-yuio, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  clusterChecksRunner:
    priorityClassName: datadog-priority-class
    resources:
      requests:
        cpu: 800m
        memory: 1024Mi
      limits:
        cpu: 1200m
        memory: 2048Mi
    deploymentAnnotations:
      manawa/cluster_name: gke-scdp-prod-yuio
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-scdp-prod-yuio
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-scdp-prod-yuio
      manawa/environment: prod
  agents:
    podLabels:
      manawa/cluster_name: gke-scdp-prod-yuio
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-scdp-prod-yuio
      manawa/environment: prod
    containers:
      agent:
        resources:
          requests:
            cpu: 1000m
            memory: 4096Mi
          limits:
            cpu: 4000m
            memory: 8192Mi
      processAgent:
        env:
        - name: DD_SCRUB_ARGS
          value: "true"
        - name: DD_CUSTOM_SENSITIVE_WORDS
          value: "*license*,*token*"
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-scdp-prod-yuio
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-scdp-prod-yuio
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-scdp-prod-yuio
      manawa/environment: prod
