apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obs-dcgm-exporter-dev
  namespace: tp-dcgm-exporter
spec:
  destination:
    namespace: tp-dcgm-exporter
    name: gke-cc-dev-tool
  project: dcgm-exporter
  source:
    path: charts/dcgm-exporter/appsets/argocd-dev
    repoURL: git@github.com:adeo/OBS-HelmDatadog.git
    targetRevision: main
    directory:
      recurse: false
