datadog:
  apmtraceportforward: true
  datadog:
    clusterName: prod-08-bea7
    tags: [manawa-cluster:prod-08-bea7, platform:ccdp, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  clusterChecksRunner:
    env:
      - name: DD_KUBERNETES_APISERVER_CLIENT_TIMEOUT
        value : 120
    priorityClassName: datadog-priority-class
    resources:
      requests:
        cpu: 800m
        memory: 1024Mi
      limits:
        cpu: 8000m
        memory: 8000Mi
    deploymentAnnotations:
      manawa/cluster_name: prod-08-bea7
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: prod-08-bea7
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: prod-08-bea7
      manawa/environment: prod
  agents:
    containers:
      agent:
        resources:
          requests:
            cpu: 1000m
            memory: 2048Mi
          limits:
            cpu: 4000m
            memory: 8192Mi
    podLabels:
      manawa/cluster_name: prod-08-bea7
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: prod-08-bea7
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: prod-08-bea7
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: prod-08-bea7
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: prod-08-bea7
      manawa/environment: prod
    resources:
      limits:
        memory: 3Gi
