version: 2
updates:
  - package-ecosystem: "docker"
    directory: "charts/datadog/datadog-dev"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "charts/datadog/datadog-nprd"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "charts/datadog/datadog-prod"
    target-branch: "main"
    schedule:
      interval: "weekly"