datadog:
  datadog:
    clusterName: gke-itdp-nprd-dati
    tags: [manawa-cluster:gke-itdp-nprd-dati, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-itdp-nprd-dati
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-itdp-nprd-dati
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-itdp-nprd-dati
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-itdp-nprd-dati
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-itdp-nprd-dati
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-itdp-nprd-dati
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-itdp-nprd-dati
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-itdp-nprd-dati
      manawa/environment: prep
