datadog:
  datadog:
    clusterName: gke-itgo-nprd-pise
    tags: [manawa-cluster:gke-itgo-nprd-pise, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-itgo-nprd-pise
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-itgo-nprd-pise
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-itgo-nprd-pise
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-itgo-nprd-pise
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-itgo-nprd-pise
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-itgo-nprd-pise
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-itgo-nprd-pise
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-itgo-nprd-pise
      manawa/environment: prep
