datadog:
  datadog:
    clusterName: gke-rolm-prod-wick
    tags: [manawa-cluster:gke-rolm-prod-wick, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-rolm-prod-wick
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-rolm-prod-wick
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-rolm-prod-wick
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-rolm-prod-wick
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-rolm-prod-wick
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-rolm-prod-wick
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-rolm-prod-wick
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-rolm-prod-wick
      manawa/environment: prod
