datadog:
  datadog:
    clusterName: gke-enki-nprd-ohm
    tags: [manawa-cluster:gke-enki-nprd-ohm, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    priorityClassName: datadog-priority-class
    containers:
      initContainers:
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 5000m
            memory: 8000Mi
      agent:
        resources:
          requests:
            cpu: 1000m
            memory: 2048Mi
          limits:
            cpu: 2000m
            memory: 4096Mi
    podLabels:
      manawa/cluster_name: gke-enki-nprd-ohm
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-enki-nprd-ohm
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-enki-nprd-ohm
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-enki-nprd-ohm
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-enki-nprd-ohm
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-enki-nprd-ohm
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-enki-nprd-ohm
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-enki-nprd-ohm
      manawa/environment: prep
