datadog:
  datadog:
    clusterName: gke-frlm-prod-peak
    tags: [manawa-cluster:gke-frlm-prod-peak, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-frlm-prod-peak
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-frlm-prod-peak
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-frlm-prod-peak
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-frlm-prod-peak
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-frlm-prod-peak
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-frlm-prod-peak
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-frlm-prod-peak
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-frlm-prod-peak
      manawa/environment: prod
