global:
  cloud_provider: gke
datadog:
  datadog:
    clusterName: gke-mesh-nprd-mars
    tags: [manawa-cluster:gke-mesh-nprd-mars, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-mesh-nprd-mars
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-mesh-nprd-mars
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-mesh-nprd-mars
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-mesh-nprd-mars
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-mesh-nprd-mars
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-mesh-nprd-mars
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-mesh-nprd-mars
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-mesh-nprd-mars
      manawa/environment: prep
