datadog:
  datadog:
    clusterName: gke-itlm-nprd-lirr
    tags: [manawa-cluster:gke-itlm-nprd-lirr, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-itlm-nprd-lirr
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-itlm-nprd-lirr
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-itlm-nprd-lirr
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-itlm-nprd-lirr
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-itlm-nprd-lirr
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-itlm-nprd-lirr
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-itlm-nprd-lirr
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-itlm-nprd-lirr
      manawa/environment: prep
