datadog:
  datadog:
    clusterName: gke-cc-dev-tool
    tags: [manawa-cluster:gke-cc-dev-tool, managed_by:observability_team, cluster_slo:true, obs-env:dev]
  agents:
    podLabels:
      manawa/cluster_name: gke-cc-dev-tool
      manawa/environment: dev
    podAnnotations:
      manawa/cluster_name: gke-cc-dev-tool
      manawa/environment: dev
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-cc-dev-tool
      manawa/environment: dev
    podAnnotations:
      manawa/cluster_name: gke-cc-dev-tool
      manawa/environment: dev
    additionalLabels:
      manawa/cluster_name: gke-cc-dev-tool
      manawa/environment: dev
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-cc-dev-tool
      manawa/environment: dev
    podAnnotations:
      manawa/cluster_name: gke-cc-dev-tool
      manawa/environment: dev
    additionalLabels:
      manawa/cluster_name: gke-cc-dev-tool
      manawa/environment: dev