datadog:
  datadog:
    clusterName: gke-brom-prod-voli
    tags: [manawa-cluster:gke-brom-prod-voli, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-brom-prod-voli
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-brom-prod-voli
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-brom-prod-voli
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-brom-prod-voli
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-brom-prod-voli
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-brom-prod-voli
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-brom-prod-voli
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-brom-prod-voli
      manawa/environment: prod
