global:
  cloud_provider: gke
datadog:
  datadog:
    clusterName: gke-eslm-nprd-hary
    tags: [manawa-cluster:gke-eslm-nprd-hary, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-eslm-nprd-hary
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-eslm-nprd-hary
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-eslm-nprd-hary
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-eslm-nprd-hary
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-eslm-nprd-hary
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-eslm-nprd-hary
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-eslm-nprd-hary
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-eslm-nprd-hary
      manawa/environment: prep
