datadog:
  datadog:
    clusterName: gke-itgo-prod-aren
    tags: [manawa-cluster:gke-itgo-prod-aren, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-itgo-prod-aren
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-itgo-prod-aren
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-itgo-prod-aren
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-itgo-prod-aren
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-itgo-prod-aren
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-itgo-prod-aren
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-itgo-prod-aren
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-itgo-prod-aren
      manawa/environment: prod
