datadog:
  datadog:
    clusterName: gke-pllm-nprd-paul
    tags: [manawa-cluster:gke-pllm-nprd-paul, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    containers:
      agent:
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 4096Mi
    podLabels:
      manawa/cluster_name: gke-pllm-nprd-paul
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-pllm-nprd-paul
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-pllm-nprd-paul
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-pllm-nprd-paul
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-pllm-nprd-paul
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-pllm-nprd-paul
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-pllm-nprd-paul
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-pllm-nprd-paul
      manawa/environment: prep
