datadog:
  datadog:
    clusterName: gke-dip-nprd-indu
    tags: [manawa-cluster:gke-dip-nprd-indu, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-dip-nprd-indu
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-dip-nprd-indu
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-dip-nprd-indu
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-dip-nprd-indu
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-dip-nprd-indu
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-dip-nprd-indu
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-dip-nprd-indu
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-dip-nprd-indu
      manawa/environment: prep
