datadog:
  datadog:
    clusterName: gke-brom-nprd-ashe
    tags: [manawa-cluster:gke-brom-nprd-ashe, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-brom-nprd-ashe
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-brom-nprd-ashe
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-brom-nprd-ashe
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-brom-nprd-ashe
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-brom-nprd-ashe
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-brom-nprd-ashe
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-brom-nprd-ashe
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-brom-nprd-ashe
      manawa/environment: prep
