datadog:
  datadog:
    clusterName: gke-ualm-prod-beer
    tags: [manawa-cluster:gke-ualm-prod-beer, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-ualm-prod-beer
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-ualm-prod-beer
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-ualm-prod-beer
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-ualm-prod-beer
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-ualm-prod-beer
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-ualm-prod-beer
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-ualm-prod-beer
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-ualm-prod-beer
      manawa/environment: prod
