datadog:
  datadog:
    clusterName: gke-dp4p-prod-nuts
    tags: [manawa-cluster:gke-dp4p-prod-nuts, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-dp4p-prod-nuts
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-dp4p-prod-nuts
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-dp4p-prod-nuts
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-dp4p-prod-nuts
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-dp4p-prod-nuts
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-dp4p-prod-nuts
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-dp4p-prod-nuts
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-dp4p-prod-nuts
      manawa/environment: prod
