datadog:
  datadog:
    clusterName: gke-itlm-prod-pugy
    tags: [manawa-cluster:gke-itlm-prod-pugy, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-itlm-prod-pugy
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-itlm-prod-pugy
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-itlm-prod-pugy
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-itlm-prod-pugy
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-itlm-prod-pugy
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-itlm-prod-pugy
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-itlm-prod-pugy
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-itlm-prod-pugy
      manawa/environment: prod
