apiVersion: v2
name: datadog-agent-umbrella
description: Datadog Agent
type: application
version: 0.1.0
dependencies:
  - name: datadog
    version: 3.71.2
    repository: "https://helm.datadoghq.com"
