datadog:
  datadog:
    clusterName: gke-rolm-nprd-john
    tags: [manawa-cluster:gke-rolm-nprd-john, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-rolm-nprd-john
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-rolm-nprd-john
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-rolm-nprd-john
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-rolm-nprd-john
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-rolm-nprd-john
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-rolm-nprd-john
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-rolm-nprd-john
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-rolm-nprd-john
      manawa/environment: prep
