datadog:
  datadog:
    clusterName: gke-ittm-prod-gold
    tags: [manawa-cluster:gke-ittm-prod-gold, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-ittm-prod-gold
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-ittm-prod-gold
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-ittm-prod-gold
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-ittm-prod-gold
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-ittm-prod-gold
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-ittm-prod-gold
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-ittm-prod-gold
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-ittm-prod-gold
      manawa/environment: prod
