global:
  cloud_provider: gke
datadog:
  datadog:
    clusterName: gke-eod-prod-jade
    tags: [manawa-cluster:gke-eod-prod-jade, managed_by:observability_team, cluster_slo:true, obs-env:main]
  agents:
    podLabels:
      manawa/cluster_name: gke-eod-prod-jade
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-eod-prod-jade
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-eod-prod-jade
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-eod-prod-jade
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-eod-prod-jade
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-eod-prod-jade
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-eod-prod-jade
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-eod-prod-jade
      manawa/environment: prod
