datadog:
  datadog:
    clusterName: gke-cc-prod-tool
    tags: [manawa-cluster:gke-cc-prod-tool, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-cc-prod-tool
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-cc-prod-tool
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-cc-prod-tool
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-cc-prod-tool
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-cc-prod-tool
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-cc-prod-tool
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-cc-prod-tool
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-cc-prod-tool
      manawa/environment: prod
