datadog:
  datadog:
    clusterName: gke-ptlm-nprd-sarl
    tags: [manawa-cluster:gke-ptlm-nprd-sarl, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-ptlm-nprd-sarl
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-ptlm-nprd-sarl
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-ptlm-nprd-sarl
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-ptlm-nprd-sarl
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-ptlm-nprd-sarl
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-ptlm-nprd-sarl
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-ptlm-nprd-sarl
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-ptlm-nprd-sarl
      manawa/environment: prep
