datadog:
  datadog:
    clusterName: gke-esom-prod-bart
    tags: [manawa-cluster:gke-esom-prod-bart, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-esom-prod-bart
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-esom-prod-bart
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-esom-prod-bart
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-esom-prod-bart
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-esom-prod-bart
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-esom-prod-bart
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-esom-prod-bart
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-esom-prod-bart
      manawa/environment: prod
