datadog:
  datadog:
    clusterName: gke-brlm-nprd-bees
    tags: [manawa-cluster:gke-brlm-nprd-bees, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-brlm-nprd-bees
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-brlm-nprd-bees
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-brlm-nprd-bees
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-brlm-nprd-bees
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-brlm-nprd-bees
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-brlm-nprd-bees
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-brlm-nprd-bees
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-brlm-nprd-bees
      manawa/environment: prep
