datadog:
  datadog:
    clusterName: gke-dxp-prod-puma
    tags: [manawa-cluster:gke-dxp-prod-puma, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-dxp-prod-puma
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-dxp-prod-puma
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-dxp-prod-puma
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-dxp-prod-puma
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-dxp-prod-puma
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-dxp-prod-puma
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-dxp-prod-puma
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-dxp-prod-puma
      manawa/environment: prod
