datadog:
  datadog:
    clusterName: gke-frlm-nprd-fall
    tags: [manawa-cluster:gke-frlm-nprd-fall, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
    # logLevel: DEBUG
  agents:
    containers:
      agent:
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 4096Mi
    podLabels:
      manawa/cluster_name: gke-frlm-nprd-fall
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-frlm-nprd-fall
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-frlm-nprd-fall
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-frlm-nprd-fall
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-frlm-nprd-fall
      manawa/environment: prep
    resources:
      requests:
        cpu: 500m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 2048Mi
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-frlm-nprd-fall
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-frlm-nprd-fall
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-frlm-nprd-fall
      manawa/environment: prep
