datadog:
  datadog:
    clusterName: gke-frlm-prod-rise
    tags: [manawa-cluster:gke-frlm-prod-rise, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    containers:
      agent:
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 4096Mi
    podLabels:
      manawa/cluster_name: gke-frlm-prod-rise
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-frlm-prod-rise
      manawa/environment: prod
  clusterChecksRunner:
    env:
      - name: DD_KUBERNETES_APISERVER_CLIENT_TIMEOUT
        value : 120
    priorityClassName: datadog-priority-class
    resources:
      requests:
        cpu: 500m
        memory: 1024Mi
      limits:
        cpu: 6000m
        memory: 6000Mi
    deploymentAnnotations:
      manawa/cluster_name: gke-frlm-prod-rise
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-frlm-prod-rise
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-frlm-prod-rise
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-frlm-prod-rise
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-frlm-prod-rise
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-frlm-prod-rise
      manawa/environment: prod
