datadog:
  datadog:
    clusterName: gke-hf3p-nprd-kobe
    tags: [manawa-cluster:gke-hf3p-nprd-kobe, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-hf3p-nprd-kobe
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-hf3p-nprd-kobe
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-hf3p-nprd-kobe
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-hf3p-nprd-kobe
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-hf3p-nprd-kobe
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-hf3p-nprd-kobe
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-hf3p-nprd-kobe
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-hf3p-nprd-kobe
      manawa/environment: prep
