global:
  cloud_provider: aks
datadog:
  datadog:
    clusterName: aks-scdp-nprd-zauj
    tags: [manawa-cluster:aks-scdp-nprd-zauj, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
    kubeStateMetricsEnabled: false
    kubeStateMetricsNetworkPolicy:
      create: false
    kubeStateMetricsCore:
      enabled: true
    kubelet:
      tlsVerify: false
  agents:
    podLabels:
      manawa/cluster_name: aks-scdp-nprd-zauj
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: aks-scdp-nprd-zauj
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: aks-scdp-nprd-zauj
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: aks-scdp-nprd-zauj
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: aks-scdp-nprd-zauj
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: aks-scdp-nprd-zauj
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: aks-scdp-nprd-zauj
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: aks-scdp-nprd-zauj
      manawa/environment: prep
