datadog:
  datadog:
    clusterName: gke-pllm-prod-land
    tags: [manawa-cluster:gke-pllm-prod-land, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    containers:
      agent:
        resources:
          requests:
            cpu: 500m
            memory: 2048Mi
          limits:
            cpu: 2000m
            memory: 8192Mi
    podLabels:
      manawa/cluster_name: gke-pllm-prod-land
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-pllm-prod-land
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-pllm-prod-land
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-pllm-prod-land
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-pllm-prod-land
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-pllm-prod-land
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-pllm-prod-land
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-pllm-prod-land
      manawa/environment: prod
