global:
  cloud_provider: gke
datadog:
  datadog:
    clusterName: gke-ghr-prod-ggwp
    tags: [manawa-cluster:gke-ghr-prod-ggwp, managed_by:observability_team, cluster_slo:true, obs-env:main]
  agents:
    podLabels:
      manawa/cluster_name: gke-ghr-prod-ggwp
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-ghr-prod-ggwp
      manawa/environment: prod
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-ghr-prod-ggwp
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-ghr-prod-ggwp
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-ghr-prod-ggwp
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-ghr-prod-ggwp
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-ghr-prod-ggwp
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-ghr-prod-ggwp
      manawa/environment: prod
