datadog:
  datadog:
    clusterName: gke-enki-prod-domo
    tags: [manawa-cluster:gke-enki-prod-domo, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    priorityClassName: datadog-priority-class
    podLabels:
      manawa/cluster_name: gke-enki-prod-domo
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-enki-prod-domo
      manawa/environment: prod
    containers:
      traceAgent:
        env:
          - name: DD_APM_MAX_TPS
            value: "500"
          - name: DD_APM_EXTRA_SAMPLE_RATE
            value: "0"
          - name: DD_APM_MAX_TRACES_PER_SECOND
            value: "0"  
          - name: DD_APM_ERROR_TPS
            value: "0"
          - name: DD_APM_OBFUSCATION_MONGODB_ENABLED
            value: "true"
          - name: DD_APM_OBFUSCATION_MONGODB_KEEP_VALUES
            value: "aggregate"
      initContainers:
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 5000m
            memory: 8000Mi
      agent:
        resources:
          requests:
            cpu: 1000m
            memory: 2048Mi
          limits:
            cpu: 2000m
            memory: 4096Mi
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-enki-prod-domo
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-enki-prod-domo
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-enki-prod-domo
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-enki-prod-domo
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-enki-prod-domo
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-enki-prod-domo
      manawa/environment: prod

  obfuscation:
    mongodb:
      ## Configures obfuscation rules for spans of type "mongodb". Enabled by default.
      enabled: true
      keep_values:
        - document_id
        - template_id
