datadog:
  datadog:
    clusterName: gke-dxp-nprd-lion
    tags: [manawa-cluster:gke-dxp-nprd-lion, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-dxp-nprd-lion
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-dxp-nprd-lion
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-dxp-nprd-lion
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-dxp-nprd-lion
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-dxp-nprd-lion
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-dxp-nprd-lion
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-dxp-nprd-lion
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-dxp-nprd-lion
      manawa/environment: prep
