datadog:
  datadog:
    clusterName: gke-dip-prod-stry
    tags: [manawa-cluster:gke-dip-prod-stry, managed_by:observability_team, cluster_slo:true, obs-env:prod]
  agents:
    podLabels:
      manawa/cluster_name: gke-dip-prod-stry
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-dip-prod-stry
      manawa/environment: prod
    containers:
      agent:
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 1000m
            memory: 8192Mi
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-dip-prod-stry
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-dip-prod-stry
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-dip-prod-stry
      manawa/environment: prod
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-dip-prod-stry
      manawa/environment: prod
    podAnnotations:
      manawa/cluster_name: gke-dip-prod-stry
      manawa/environment: prod
    additionalLabels:
      manawa/cluster_name: gke-dip-prod-stry
      manawa/environment: prod
