datadog:
  datadog:
    clusterName: gke-frlm-nprd-base
    tags: [manawa-cluster:gke-frlm-nprd-base, managed_by:observability_team, cluster_slo:true, obs-env:nprd]
  agents:
    podLabels:
      manawa/cluster_name: gke-frlm-nprd-base
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-frlm-nprd-base
      manawa/environment: prep
  clusterChecksRunner:
    deploymentAnnotations:
      manawa/cluster_name: gke-frlm-nprd-base
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-frlm-nprd-base
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-frlm-nprd-base
      manawa/environment: prep
  clusterAgent:
    deploymentAnnotations:
      manawa/cluster_name: gke-frlm-nprd-base
      manawa/environment: prep
    podAnnotations:
      manawa/cluster_name: gke-frlm-nprd-base
      manawa/environment: prep
    additionalLabels:
      manawa/cluster_name: gke-frlm-nprd-base
      manawa/environment: prep
